import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const root = path.resolve('apps/web/package.json');
const manifest = JSON.parse(fs.readFileSync(root, 'utf8'));
const found = new Map();

function walk(name, from) {
  const resolve = createRequire(from).resolve;
  let file;
  try {
    file = resolve(name + '/package.json');
  } catch {
    try {
      let directory = path.dirname(resolve(name));
      while (directory !== path.dirname(directory)) {
        const candidate = path.join(directory, 'package.json');
        if (fs.existsSync(candidate) && JSON.parse(fs.readFileSync(candidate, 'utf8')).name === name) {
          file = candidate;
          break;
        }
        directory = path.dirname(directory);
      }
    } catch {
      return; // Optional platform dependency absent on this machine.
    }
  }
  if (!file) return;
  file = fs.realpathSync(file);
  const item = JSON.parse(fs.readFileSync(file, 'utf8'));
  const key = `${item.name}@${item.version}`;
  if (found.has(key)) return;
  found.set(key, item);
  for (const dependency of Object.keys({ ...item.dependencies, ...item.optionalDependencies })) {
    walk(dependency, file);
  }
}
for (const name of Object.keys({ ...manifest.dependencies, ...manifest.devDependencies })) walk(name, root);
const lines = ['# Resolved frontend dependency licenses', '', 'Generated by traversing the active installed dependency graph from package.json, including development dependencies. Absent optional platform binaries are excluded. Package license files remain authoritative.', '', '| Package | Version | Declared license |', '|---|---|---|'];
for (const item of [...found.values()].sort((a, b) => a.name.localeCompare(b.name))) {
  lines.push(`| ${item.name} | ${item.version} | ${typeof item.license === 'string' ? item.license : JSON.stringify(item.license ?? 'Review package license')} |`);
}
fs.writeFileSync('docs/frontend-dependency-licenses.md', lines.join('\n') + '\n');
